# Generated by Django 4.1.3 on 2023-01-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscreteVotingZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('first_option', models.CharField(max_length=100)),
                ('second_option', models.CharField(max_length=100)),
                ('first_option_count', models.IntegerField()),
                ('second_option_count', models.IntegerField()),
            ],
        ),
    ]
