# Generated by Django 4.1.3 on 2023-01-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discretevotingz',
            name='first_option',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='discretevotingz',
            name='second_option',
            field=models.CharField(max_length=50),
        ),
    ]
