# Generated by Django 4.1.3 on 2023-01-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_discretevotingz_first_option_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscreteVotingZ',
            new_name='DiscreteVotings',
        ),
    ]
