# Generated by Django 4.1.3 on 2023-02-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_votefact_votevariant_voting_delete_discretevotings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
