# Generated by Django 4.1.3 on 2023-02-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
