# Generated by Django 4.1.3 on 2023-02-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Жалоба отправлена на рассмотрение', max_length=100),
            preserve_default=False,
        ),
    ]
